### ISSUE TITLE
Failed to start on Ubuntu 22.04 LTS: arguments did not match any overloaded call of QRect

### ISSUE THREAD

**Issue by tpimh** [multigcs/viaconstructor#7]
Using Python 3.10.12, all requirements were installed successfully with pip.
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "̣…/viaconstructor/viaconstructor/__main__.py", line 4, in <module>
    ViaConstructor()
  File "…/viaconstructor/viaconstructor/viaconstructor.py", line 3133, in __init__
    self.gear_tool = GearTool(self)
  File "…/viaconstructor/viaconstructor/tools/gear.py", line 223, in __init__
    self.preview()
  File "…/viaconstructor/viaconstructor/tools/gear.py", line 267, in preview
    square = QRect(
TypeError: arguments did not match any overloaded call:
  QRect(): too many arguments
  QRect(int, int, int, int): argument 1 has unexpected type 'float'
  QRect(QPoint, QPoint): argument 1 has unexpected type 'float'
  QRect(QPoint, QSize): argument 1 has unexpected type 'float'
  QRect(QRect): argument 1 has unexpected type 'float'
QPaintDevice: Cannot destroy paint device that is being painted
```

**Comment by multigcs** [comment]
https://github.com/multigcs/viaconstructor/commit/8444750d50098ed69393a642efa42a6a5eb1a95f

**Comment by tpimh** [comment]
Thanks for the quick fix!

**Comment by multigcs** [comment]
Hope it work's, on my system (maybe older qt version) also works with float's

**Comment by tpimh** [comment]
It does work :)
![Screenshot from 2024-02-06 16-19-29](https://github.com/multigcs/viaconstructor/assets/1071872/97de2c8a-9452-4c7e-af7e-e9b5ac9955d7)
