### ISSUE TITLE
Invalid arguments (float) to `QRect`

### ISSUE THREAD

**Issue by faern** [multigcs/viaconstructor#8]
Hi. I just tried this tool on Fedora 39 with Python 3.12. I installed it via pip and then the remaining requirements via `dnf`. When I try to start `viaconstructor` I get this error:

```
$ viaconstructor
WARNING: please install newer version of ezdxf: cannot import name 'fonts' from 'ezdxf.tools' (/home/faern/.local/lib/python3.12/site-packages/ezdxf/tools/__init__.py)
Failed to create wl_display (No such file or directory)
qt.qpa.plugin: Could not load the Qt platform plugin "wayland" in "" even though it was found.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/faern/.local/lib/python3.12/site-packages/viaconstructor/__main__.py", line 4, in <module>
    ViaConstructor()
  File "/home/faern/.local/lib/python3.12/site-packages/viaconstructor/viaconstructor.py", line 3133, in __init__
    self.gear_tool = GearTool(self)
                     ^^^^^^^^^^^^^^
  File "/home/faern/.local/lib/python3.12/site-packages/viaconstructor/tools/gear.py", line 223, in __init__
    self.preview()
  File "/home/faern/.local/lib/python3.12/site-packages/viaconstructor/tools/gear.py", line 267, in preview
    square = QRect(
             ^^^^^^
TypeError: arguments did not match any overloaded call:
  QRect(): too many arguments
  QRect(aleft: int, atop: int, awidth: int, aheight: int): argument 1 has unexpected type 'float'
  QRect(atopLeft: QPoint, abottomRight: QPoint): argument 1 has unexpected type 'float'
  QRect(atopLeft: QPoint, asize: QSize): argument 1 has unexpected type 'float'
  QRect(a0: QRect): argument 1 has unexpected type 'float'
QPaintDevice: Cannot destroy paint device that is being painted
```

Maybe `PyQt5` changed to require int now and accepted float in an earlier version?

I tried running it in X11 mode also. The warning at the top goes away, but it still crash with the same `QRect` error, so I think it's unrelated.

**Comment by multigcs** [comment]
sorry, forget to upload the new version, the 'int' was already fixed in git.
you can update to version 0.6.6.

but don't know how i can fix the 'wayland' problem

**Comment by faern** [comment]
Thanks for the quick reply! That solved the `QRect` error! The program now starts. From an initial 5 second look it seems to work when running under XWayland, which I guess is good enough for now. Will have to play around with it and learn more aspects of the tool.

Thank you for creating this CAM-tool :heart:
